### ISSUE TITLE
Vertical centering seems impossible to disable from Rise

### ISSUE THREAD

**Issue by pmjandreen** [damianavila/RISE#166]
Reveal has the following option for choosing vertical alignment style:

```
// Vertical centering of slides
center: true
```

I find that when I try to set center to false using Rise it has no effect (I tried both ways of configuring Reveal from Rise).

**Comment by damianavila** [comment]
It could be some problems with the notebook css... this need to be investigated...

**Comment by damianavila** [comment]
@pmjandreen how did you try to set this false... my best guess is modifying the source code. But I would like confirmation before proceeding with the discussion and possible fix/enhancement.

**Comment by pmjandreen** [comment]
I tried both ways of configuring Reveal from Rise (in the code and in the metadata of the notebook).

**Comment by damianavila** [comment]
@pmjandreen thanks for the info, I will take a look.

**Comment by kevin-keraudren** [comment]
In order to disable centering, you need to set if to `false` in reveal.js, as you already did, but you also need to add a few lines to `~/.jupyter/custom/custom.css`:

```css
.my-outer-container {
    width:100%;
    height:100%;
    position:absolute;
    display:table;
}
.my-center-container {
    display:table-cell;
    vertical-align:middle;
    width:100%;
    height:100%:
}
```

see notebook here https://github.com/kevin-keraudren/pydata-meetup-20161101 which gets rendered like this http://www.slideshare.net/kevinkeraudren/medical-imaging-in-python-from-morphological-operations-to-machine-learning-and-visualisation
