### ISSUE TITLE
Control buttons of nbtutor disappear when going in RISE live show mode

### ISSUE THREAD

**Issue by Naereen** [damianavila/RISE#587]
Hello there,
I'm opening this issue here, but I don't expect a reaction from RISE, but more from the other side, of the [nbtutor](https://github.com/lgpage/nbtutor/) extension developpers.
But opening this issue here means that if someone encounters the same bug as I did, they will be able to know why!

---

This extension works very well for me, and I'm a big fan and intense user of [the RISE jupyter extension](https://rise.readthedocs.io/en/stable/) to teach with Jupyter notebook being displayed in full screen as slides.

As shown in this demo:
![Peek 21-02-2021 03-04](https://user-images.githubusercontent.com/11994719/108613393-d9018480-73f1-11eb-8c93-eb9642235c58.gif)

using nbtutor from the RISE live show mode (regardless of being full-screen) works from the backend side, but not from the frontend UI side: the control buttons are hidden!
But exiting the RISE mode shows that the buttons are there, they work and everything is fine.

**Comment by Naereen** [comment]
So, I found what to change on RISE css, just delete or disable this rule!
```css
.rise-enabled.ctb_global_show .ctb_hideshow.ctb_show {
    display: none;
}
```
![Peek 21-02-2021 03-22](https://user-images.githubusercontent.com/11994719/108613655-3dbdde80-73f4-11eb-9b21-934887a48443.gif)

So it's this line:
https://github.com/damianavila/RISE/blob/ed64f2fe81b7d26ee34c96f4dfdfbf74cdae7fb7/classic/src/less/main.less#L111
```less
.rise-enabled {
  [...]
  &.ctb_global_show {
    .ctb_hideshow.ctb_show { display: none; }
    .ctb_show ~ .text_cell_render { border-style: none; }
  }
```

**Comment by Naereen** [comment]
I guess the easiest way to go, if someone encounters the same issue, is to use [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/)

And this [CSS userstyle](https://userstyles.org):
```css
@-moz-document regexp("https?://localhost:[0-9]*/notebooks/.*#/slide.*") {
/* New CSS style to show Jupyter celltoolbar when RISE live show mode is enabled.
 * See https://github.com/lgpage/nbtutor/issues/42
 * Released under the term of the MIT Licence (https://lbesson.mit-license.org/)
 * By Lilian Besson, © 2021
 * To use with Stylus, see https://userstyles.org
**/
.rise-enabled.ctb_global_show .ctb_hideshow.ctb_show {
    display: inherit !important;
}
}
```
[source](https://perso.crans.org/besson/publis/firefox/stylus-show-Jupyter-celltoolbar-when-RISE-live-show-mode-is-enabled.user.css)
