### ISSUE TITLE
Lost custom css style when downloading as reveal.js slides html

### ISSUE THREAD

**Issue by lemuellew** [damianavila/RISE#641]
I put h1 tag on the top in `rise.css`, the style lost when downloading as reveal.js slides html 
```css
h1 {
  position: fixed;
  top: 0;
}
```
